DABanDan/DABanDan/Controllers/CartController.cs
using DABanDan.Common;
using DABanDan.DAO;
using DABanDan.InputModels.GioHang;
using DABanDan.Models;
using DABanDan.OutPutModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace DABanDan.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            List<GioHang> cart = Session[CommonConstans.CartSession] as List<GioHang>;
  
            return View(cart);
        }
        //view indẽ gio hang
        //-------------------------------Xóa tat ca Gio Hàng--------------------------------------------------
        //public RedirectToRouteResult DeleteAll()
        //{
        //    List<GioHang> giohang = Session[CommonConstans.CartSession] as List<GioHang>;
        //    GioHang itemXoa = giohang.FirstOrDefault(m => m.MaSP == SanPhamID);
        //    if (itemXoa != null)
        //    {
        //        giohang.Remove(itemXoa);
        //    }
        //    return RedirectToAction("Index");
        //}
        //-------------------------------Xóa 1 sp--------------------------------------------------
        public RedirectToRouteResult Delete(int SanPhamID)
        {
            List<GioHang> giohang = Session[CommonConstans.CartSession] as List<GioHang>;
            GioHang itemXoa = giohang.FirstOrDefault(m => m.MaSP == SanPhamID);
            if (itemXoa != null)
            {
                giohang.Remove(itemXoa);
            }
            return RedirectToAction("Index");
        }
        //-------------------------------Cập nhật Gio Hàng--------------------------------------------------
        public RedirectToRouteResult Update(int SanPhamID, int soluongmoi)
        {
            // tìm carditem muon sua
            List<GioHang> giohang = Session[CommonConstans.CartSession] as List<GioHang>;
            GioHang itemSua = giohang.FirstOrDefault(m => m.MaSP == SanPhamID);
            if (itemSua != null)
            {
                itemSua.SoLuong = soluongmoi;
            }
            return RedirectToAction(nameof(Index));
        }
        //-------------------------------Thêm sp vào Giỏ Hàng--------------------------------------------------
        public RedirectToRouteResult AddItem(int maSP)
        {
            if (Session[CommonConstans.CartSession] == null) // Nếu giỏ hàng chưa được khởi tạo
            {
                Session[CommonConstans.CartSession] = new List<GioHang>();  // Khởi tạo Session["giohang"] là 1 List<CartItem>
            }

            List<GioHang> giohang = Session[CommonConstans.CartSession] as List<GioHang>;  // Gán qua biến giohang dễ code

            // Kiểm tra xem sản phẩm khách đang chọn đã có trong giỏ hàng chưa

            if (giohang.FirstOrDefault(m => m.MaSP == maSP) == null) // ko co sp nay trong gio hang
            {
                SanPham sp = new ProductDao().ViewDetail(maSP); // tim sp theo sanPhamID// gọi hàm lấy id

                GioHang newItem = new GioHang()
                {
                    MaSP = maSP,
                    TenSP = sp.TenSP,
                    SoLuong = 1,
                    HinhAnh = sp.IMG,
                    DonGia = sp.DonGia

                };  // Tạo ra 1 CartItem mới

                giohang.Add(newItem);  // Thêm CartItem vào giỏ 
            }
            else
            {
                // Nếu sản phẩm khách chọn đã có trong giỏ hàng thì không thêm vào giỏ nữa mà tăng số lượng lên.
                GioHang cardItem = giohang.FirstOrDefault(m => m.MaSP == maSP);
                cardItem.SoLuong++;
            }

            // Action này sẽ chuyển hướng về trang chi tiết sp khi khách hàng đặt vào giỏ thành công. Bạn có thể chuyển về chính trang khách hàng vừa đứng bằng lệnh return Redirect(Request.UrlReferrer.ToString()); nếu muốn.
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public PartialViewResult CtGioHang()
        {
            var giohang = Session[CommonConstans.CartSession];
            var list = new List<GioHang>();
            if(giohang != null)
            {
                list = (List<GioHang>)giohang;
            }
            return PartialView(list);
        }

        //[HttpGet]
        //public ActionResult ThanhToan()
        //{
        //    var giohang = Session[CommonConstans.CartSession];
        //    var list = new List<GioHang>();
        //    if (giohang != null)
        //    {
        //        list = (List<GioHang>)giohang;
        //    }
        //    return View(list);
        //}

        //[HttpPost]
        //public ActionResult ThanhToan(HoaDon hoadon)
        //{
        //    var user = Session[CommonConstans.User];
        //    if (user == null)
        //    {
        //       return RedirectToAction("DangNhap", "User");
        //    }
        //    //var cart =(GioHang)Session[CommonConstans.CartSession];
        //    hoadon = new HoaDon();
        //        hoadon.NgayLHD = DateTime.Now;
        //        hoadon.NgayGiao = DateTime.Now.AddDays(3);
        //        hoadon.VAT = "10";
        //        hoadon.TinhTrang = "N";
        //        hoadon.TongTien = 10000;

        //    try
        //    {
        //        var id = new DonHangDAO().Insert(hoadon);
        //        var giohang = (List<GioHang>)Session[CommonConstans.CartSession];
        //        var chitietDAO = new ChiTietDonHangDAO();
        //        foreach (var item in giohang)
        //        {
        //            var chitiethoadon = new CTHoaDon();
        //            chitiethoadon.MaSP = item.SanPham.MaSP;
        //            chitiethoadon.MaHD = id;
        //            chitiethoadon.SoLuong = item.SanPham.SoLuong;
        //            chitiethoadon.ThanhTien = item.SanPham.DonGia;

        //            chitietDAO.Insert(chitiethoadon);
        //        }
        //    }
        //    catch (Exception)
        //    {
        //        return Redirect("/Loi-thanh-toan");
        //    }
        //    return Redirect("/hoan-thanh");
        //}

        public ActionResult ThanhCong()
        {
            return View();
        }
    }
}

DABanDan/DABanDan/Controllers/ProductController.cs
using DABanDan.DAO;
using DABanDan.InputModels.Product;
using DABanDan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DABanDan.Controllers
{
    public class ProductController : Controller
    {
        Database db = new Database();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult LoaiSP()
        {
            var model = new ProductCategoryDao().ListALL();
            return PartialView(model);
        }

        [ChildActionOnly]
        public PartialViewResult HieuSP()
        {
            var model = new ProductCategoryDao().ListALLs();
            return PartialView(model);
        }

        public ActionResult TTLoaiSP(string ml , int page = 1, int pageSize = 4)
        {
            var kq = new CategoryDao().ViewDetail(ml);
            ViewBag.TTLoaiSP = kq;
            int totalRecord = 0;
            var model = new ProductDao().DSLoaiSP(ml,ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return View(model);
        }

        public ActionResult TTHieuSP(string mh, int page = 1, int pageSize = 6)
        {
           
         
            int totalRecord = 0;
            var model = new ProductDao().DSHieuSP(mh, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return View(model);
        }

        //-------------------------Tìm Kiếm------------------------------------------------------------
        //public ActionResult TimKiem(string keyword, int page = 1, int pageSize = 4)
        //{
           
        //    int totalRecord = 0;
        //    var model = new ProductDao().Search(keyword, ref totalRecord, page, pageSize);

        //    ViewBag.Total = totalRecord;
        //    ViewBag.Page = page;
        //    ViewBag.Keyword = keyword;
        //    int maxPage = 5;
        //    int totalPage = 0;

        //    totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
        //    ViewBag.TotalPage = totalPage;
        //    ViewBag.MaxPage = maxPage;
        //    ViewBag.First = 1;
        //    ViewBag.Last = totalPage;
        //    ViewBag.Next = page + 1;
        //    ViewBag.Prev = page - 1;
        //    return View(model);
        //}

        //-------------------------Tìm Kiếm DS Liên Quan------------------------------------------------------------
        public ActionResult ResultSearch(string q)
        {
            if (q == null)
            {
                return ViewBag.Result = "Ko có";
            }
            var result = new ProductDao().DanhSachSP(q);
            return View(result);
        }

    }
}

DABanDan/DABanDan/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DABanDan.Models;
using DABanDan.DAO;
using DABanDan.InputModels.Category;
using DABanDan.InputModels.Product;
using System.Web.UI;
using PagedList;

namespace DABanDan.Controllers
{
    public class ShopController : Controller
    {
        Database db = new Database();
        // GET: Shop
        public ActionResult Index()
        {
            var prDao = new ProductDao();
            ViewBag.lvsp = prDao.ListLVSanPham();
            ViewBag.dongiasp = prDao.ListDonGiaSanPham();    
            return View();
        }
    }
}

DABanDan/DABanDan/Controllers/UserController.cs
using DABanDan.Common;
using DABanDan.DAO;
using DABanDan.InputModels.DangKy;
using DABanDan.InputModels.DangNhap;
using DABanDan.Models;
using System.Web.Mvc;

namespace DABanDan.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(DangKyModel model)
        {

            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                if (dao.KTraEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email này đã tồn tại");
                }
                else if (dao.KTraUserName(model.TenUser))
                {
                    ModelState.AddModelError("", "Tên đăng nhập này đã tồn tại");
                }
                else
                {
                    var user = new NguoiDung();
                    user.TenUser = model.TenUser;
                    user.Ho = model.Ho;
                    user.Ten = model.Ten;
                    user.Email = model.Email;
                    user.SDT = model.SDT;
                    user.MatKhau = model.MatKhau;
                    user.DiaChi = model.DiaChi;

                    var dem = dao.Insert(user);
                    if (dem.Length > 0)
                    {
                        ViewBag.Success = "Đăng Ký thành công";
                        model = new DangKyModel();
                    }
                    else
                    {
                        ViewBag.Success = "Đăng Ký không thành công";
                    }
                }
            }
            return View(model);
        }

        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(DangNhapModel model)
        {
            {
                if (ModelState.IsValid)
                {
                    var dao = new UserDao();
                    var kq = dao.Login(model.TenUser, model.MatKhau);
                    if (kq)
                    {
                        var user = dao.GetById(model.TenUser);
                        UserLogin userSesion = new UserLogin();
                        Session.Add(CommonConstans.User, userSesion);
                            userSesion.UserName = user.TenUser;
                            userSesion.UserID = user.MaND;
                            userSesion.DiaChi = user.DiaChi;

                        Session.Add(CommonConstans.USER_SESSION, userSesion);
                        return RedirectToAction("Index", "Default");
                    }
                    else
                    {
                        ViewBag.Error = "Tài khoản hoặc Mật khẩu không chính xác";
                    }

                }
                else
                {
                    ModelState.AddModelError("Error", "Lỗi !");
                }
                return View(model);
            }
        }

        public ActionResult DangXuat()
        {
            Session[CommonConstans.USER_SESSION] = null;
            return Redirect("/");
        }


    }
}

DABanDan/DABanDan/Views/Shared/CtGioHang.cshtml
@using DABanDan.Common
@model List<DABanDan.InputModels.GioHang.GioHang>


<hr />
    <div class="cart-fav-search mb-100">
        @{
            var session = (UserLogin)Session[DABanDan.Common.CommonConstans.USER_SESSION];
        }
        @if (session == null)
        {
            <a href="@Url.Action("DangNhap","User")" class="fav-nav"><img src="~/Content/Client/img/core-img/favorites.png" alt="">Đăng Nhập</a>
        }
        else
        {
            <ul>
                <center>
                    <li style="font-family: 'Times New Roman'">Xin Chào: @session.UserName </li>
                    <a style="font-family: 'Times New Roman';color:lightseagreen" href="@Url.Action("DangXuat", "User")">OUT</a>
                </center> 
            </ul>
        }
        <a href="@Url.Action("Index","Cart")" class="cart-nav"><img src="~/Content/Client/img/core-img/cart.png" alt="">Giỏ Hàng<span>(@Model.Count)</span></a>
        <a href="#" class="search-nav"><img src="~/Content/Client/img/core-img/search.png" alt="">Tìm Kiếm</a>
    </div>

DABanDan/DABanDan/Views/Shared/HieuSP.cshtml
@model List<DABanDan.Models.HieuDan>
@{
    ViewBag.Title = "Trang chủ bán hàng | Shop";
}
 <!-- ##### BRAND ##### -->
<div class="widget brands mb-50">
    <!-- Widget Title -->
    <h6 class="widget-title mb-30" style="font-family:'Times New Roman'" >____HIỆU ĐÀN</h6>
    <div class="catagories-menu">
        <ul>
            @foreach (var item in Model)
            {
                <li><a href="@Url.Action("TTHieuSP","Product", new { mh = item.MaHieu })">@item.TenHieu</a></li>
            }
        </ul>
    </div>
    
</div>

DABanDan/DABanDan/Views/Shared/LoaiSP.cshtml
@model List<DABanDan.Models.LoaiDan>
@{ 
    ViewBag.Title = "Trang chủ bán hàng | Shop";
}
    <!-- ##### CAGETORY ##### -->
        <!-- Widget Title -->
        <h6 class="widget-title mb-10" style="font-family:'Times New Roman'">____LOẠI ĐÀN</h6>
        <!--  Catagories  -->
        <div class="catagories-menu">
            <ul>
                @foreach (var item in Model)
                {
                    <li><a href="/san-pham/@item.MaLoai">@item.TenLoai</a></li>
                }
            </ul>
        </div>
 

DABanDan/DABanDan/Views/Shared/TTHieuSP.cshtml
@model List<DABanDan.Models.SanPham>
@{
    ViewBag.Title = "Hiệu Đàn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="shop_sidebar_area">
    <!-- ##### CAGETORY ##### -->
    <div class="widget catagory mb-50">
        @{ Html.RenderAction("LoaiSP", "Product");}
    </div>

    <!-- ##### BRAND ##### -->
    <div class="widget brands mb-50">
        @{ Html.RenderAction("HieuSP", "Product");}
    </div>

    <!-- ##### COLOR ##### -->
    <div class="widget color mb-50">
        <!-- Widget Title -->
        <h6 class="widget-title mb-30">Màu Sắc</h6>
        <div class="widget-desc">
            <ul class="d-flex">
                <li><a href="#" class="color3"></a></li>
                <li><a href="#" class="color1"></a></li>
                <li><a href="#" class="color6"></a></li>
                <li><a href="#" class="color7"></a></li>
            </ul>
        </div>
    </div>
</div>

<div class="amado_product_area section-padding-100">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="product-topbar d-xl-flex align-items-end justify-content-between">
                    <!-- SXSorting -->
                    <div class="product-sorting d-flex">
                        <div class="sort-by-date d-flex align-items-center mr-15">
                            <p>Sắp Xếp theo</p>
                            <form action="#" method="get">
                                <select name="select" id="sortBydate">
                                    <option value="value">__Giá Guitar</option>
                                    <option value="value">__Sản phẩm mới</option>
                                </select>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- Single Product Area -->
            @if (Model.Count > 0)
            {
                foreach (var item in Model)
                {
                <div class="col-12 col-sm-6 col-md-12 col-xl-6">
                    <div class="single-product-wrapper">
                        <!-- Product Image -->
                        <div class="product-img">
                            <a href="@Url.Action("Detail", "Default", new { id = @item.MaSP })">
                                <img src="@item.IMG" alt="" style="width: 50%">
                            </a>
                        </div>
                        <!-- Product Description -->
                        <div class="product-description d-flex align-items-center justify-content-between">
                            <!-- Product Meta Data -->
                            <div class="product-meta-data">
                                <div class="line"></div>
                                <a href="@Url.Action("Detail", "Default", new { id = @item.MaSP })">
                                    <p style="font-family:'Times New Roman';"  class="product-price">@item.DonGia.ToString("#,##0").Replace(',', '.') VND</p>
                                    <h6>@item.TenSP</h6>
                                </a>
                            </div>
                            <!-- Cart -->
                            <div class="ratings-cart text-right">
                                <div class="cart">
                                    <a href="@Url.Action("Index", "Cart")" data-toggle="tooltip" data-placement="left" title="Add to Cart"><img src="~/Content/Client/img/core-img/cart.png" alt=""></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                }
            }
            else
            {
                <p class="container-fluid" style="font-family: 'Times New Roman'; color: red">Sản phẩm này đã hết!!!</p>
            }
        </div>
    </div>
</div>

DABanDan/DABanDan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Title  -->
    <title>Trang Chủ Guitar</title>

    <!-- Favicon  -->
    <link rel="icon" href="~/Content/Client/img/core-img/favicon.ico">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="~/Content/Client/css/core-style.css">
    <link rel="stylesheet" href="~/Content/Client/css/style.css">
    <link href="~/Content/Client/css/jquery-ui.css" rel="stylesheet" />

    <!-- Jquery -->
    <script src="~/Content/Client/js/jquery/jquery-2.2.4.min.js"></script>
    <script src="~/Content/Client/js/jquery-ui.js"></script>
</head>

<body>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        @using (Html.BeginForm("Index", "Default", FormMethod.Post))
                        {
                            @Html.TextBox("tk"); <br />
                            <input type="submit" value="Tìm kiếm" width="100" height="50" />
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Wrapper Area End -->
    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">
        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="@Url.Action("Index", "Default")"><img src="~/Content/Client/img/core-img/Logos.png" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>
        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <a href="@Url.Action("Index", "Default")"><img src="~/Content/Client/img/core-img/Logos.png" alt=""></a>
                <hr />
                <center>
                    <nav class="amado-nav">
                        <ul style="font-family: 'Times New Roman'">
                            <li><a>LH: 0385937251 </a></li>
                            </ul>
                    </nav>
                </center>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li class="active"><a href="@Url.Action("Index", "Default")">Trang Chủ</a></li>
                    <li><a href="@Url.Action("Index", "Shop")">Sản Phẩm</a></li>
                    <li><a href="@Url.Action("Index","Cart")">Giỏ Hàng</a></li>
                    <li><a href="@Url.Action("DangKy","User")">Đăng Kí</a></li>
                </ul>
            </nav>
            <!-- Cart Menu -->
            @{ Html.RenderAction("CtGioHang", "Cart");}
            <!-- Cart Menu -->
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="https://www.pinterest.com/"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="https://www.facebook.com/rom.david.7106"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </header>
        <!-- Header Area End -->
        <!-- Product Catagories Area Start -->
        @RenderBody()
    </div>
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href="@Url.Action("Index","Default")"><img width="30%" src="~/Content/Client/img/core-img/Logos.png" alt=""></a>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite">
                        </p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","Default")">Trang chủ</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index", "Shop")">Sản Phẩm</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index","Cart")">Giỏ Hàng</a>
                                        </li>
                                        <li class="nav-item active">
                                            <a class="nav-link" href="@Url.Action("LoginAdmin", "LoginAdmin", new { Area = "Admin" })">Admin(QTV)</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->
    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->

    <script src="~/Content/Client/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="~/Content/Client/js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="~/Content/Client/js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="~/Content/Client/js/plugins.js"></script>
    <!-- Active js -->
    <script src="~/Content/Client/js/active.js"></script>
    <!-- nhúng tìm kiếm js -->
    <script src="~/Areas/Client/Controller/timkiemControler.js"></script>
    <link href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet"></link>
    <script src='https://cdn.rawgit.com/pguso/jquery-plugin-circliful/master/js/jquery.circliful.min.js'></script>
    <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
    @RenderSection("jsFooter", required: false)
</body>

</html>