DABanDan/DABanDan/Controllers/CartController.cs
using DABanDan.Common;
using DABanDan.DAO;
using DABanDan.InputModels.GioHang;
using DABanDan.Models;
using DABanDan.OutPutModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace DABanDan.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            List<GioHang> cart = Session[CommonConstans.CartSession] as List<GioHang>;
  
            return View(cart);
        }
        //view indẽ gio hang
        //-------------------------------Xóa tat ca Gio Hàng--------------------------------------------------
        //public RedirectToRouteResult DeleteAll()
        //{
        //    List<GioHang> giohang = Session[CommonConstans.CartSession] as List<GioHang>;
        //    GioHang itemXoa = giohang.FirstOrDefault(m => m.MaSP == SanPhamID);
        //    if (itemXoa != null)
        //    {
        //        giohang.Remove(itemXoa);
        //    }
        //    return RedirectToAction("Index");
        //}
        //-------------------------------Xóa 1 sp--------------------------------------------------
        public RedirectToRouteResult Delete(int SanPhamID)
        {
            List<GioHang> giohang = Session[CommonConstans.CartSession] as List<GioHang>;
            GioHang itemXoa = giohang.FirstOrDefault(m => m.MaSP == SanPhamID);
            if (itemXoa != null)
            {
                giohang.Remove(itemXoa);
            }
            return RedirectToAction("Index");
        }
        //-------------------------------Cập nhật Gio Hàng--------------------------------------------------
        public RedirectToRouteResult Update(int SanPhamID, int soluongmoi)
        {
            // tìm carditem muon sua
            List<GioHang> giohang = Session[CommonConstans.CartSession] as List<GioHang>;
            GioHang itemSua = giohang.FirstOrDefault(m => m.MaSP == SanPhamID);
            if (itemSua != null)
            {
                itemSua.SoLuong = soluongmoi;
            }
            return RedirectToAction(nameof(Index));
        }
        //-------------------------------Thêm sp vào Giỏ Hàng--------------------------------------------------
        public RedirectToRouteResult AddItem(int maSP)
        {
            if (Session[CommonConstans.CartSession] == null) // Nếu giỏ hàng chưa được khởi tạo
            {
                Session[CommonConstans.CartSession] = new List<GioHang>();  // Khởi tạo Session["giohang"] là 1 List<CartItem>
            }

            List<GioHang> giohang = Session[CommonConstans.CartSession] as List<GioHang>;  // Gán qua biến giohang dễ code

            // Kiểm tra xem sản phẩm khách đang chọn đã có trong giỏ hàng chưa

            if (giohang.FirstOrDefault(m => m.MaSP == maSP) == null) // ko co sp nay trong gio hang
            {
                SanPham sp = new ProductDao().ViewDetail(maSP); // tim sp theo sanPhamID// gọi hàm lấy id

                GioHang newItem = new GioHang()
                {
                    MaSP = maSP,
                    TenSP = sp.TenSP,
                    SoLuong = 1,
                    HinhAnh = sp.IMG,
                    DonGia = sp.DonGia

                };  // Tạo ra 1 CartItem mới

                giohang.Add(newItem);  // Thêm CartItem vào giỏ 
            }
            else
            {
                // Nếu sản phẩm khách chọn đã có trong giỏ hàng thì không thêm vào giỏ nữa mà tăng số lượng lên.
                GioHang cardItem = giohang.FirstOrDefault(m => m.MaSP == maSP);
                cardItem.SoLuong++;
            }

            // Action này sẽ chuyển hướng về trang chi tiết sp khi khách hàng đặt vào giỏ thành công. Bạn có thể chuyển về chính trang khách hàng vừa đứng bằng lệnh return Redirect(Request.UrlReferrer.ToString()); nếu muốn.
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public PartialViewResult CtGioHang()
        {
            var giohang = Session[CommonConstans.CartSession];
            var list = new List<GioHang>();
            if(giohang != null)
            {
                list = (List<GioHang>)giohang;
            }
            return PartialView(list);
        }

        //[HttpGet]
        //public ActionResult ThanhToan()
        //{
        //    var giohang = Session[CommonConstans.CartSession];
        //    var list = new List<GioHang>();
        //    if (giohang != null)
        //    {
        //        list = (List<GioHang>)giohang;
        //    }
        //    return View(list);
        //}

        //[HttpPost]
        //public ActionResult ThanhToan(HoaDon hoadon)
        //{
        //    var user = Session[CommonConstans.User];
        //    if (user == null)
        //    {
        //       return RedirectToAction("DangNhap", "User");
        //    }
        //    //var cart =(GioHang)Session[CommonConstans.CartSession];
        //    hoadon = new HoaDon();
        //        hoadon.NgayLHD = DateTime.Now;
        //        hoadon.NgayGiao = DateTime.Now.AddDays(3);
        //        hoadon.VAT = "10";
        //        hoadon.TinhTrang = "N";
        //        hoadon.TongTien = 10000;

        //    try
        //    {
        //        var id = new DonHangDAO().Insert(hoadon);
        //        var giohang = (List<GioHang>)Session[CommonConstans.CartSession];
        //        var chitietDAO = new ChiTietDonHangDAO();
        //        foreach (var item in giohang)
        //        {
        //            var chitiethoadon = new CTHoaDon();
        //            chitiethoadon.MaSP = item.SanPham.MaSP;
        //            chitiethoadon.MaHD = id;
        //            chitiethoadon.SoLuong = item.SanPham.SoLuong;
        //            chitiethoadon.ThanhTien = item.SanPham.DonGia;

        //            chitietDAO.Insert(chitiethoadon);
        //        }
        //    }
        //    catch (Exception)
        //    {
        //        return Redirect("/Loi-thanh-toan");
        //    }
        //    return Redirect("/hoan-thanh");
        //}

        public ActionResult ThanhCong()
        {
            return View();
        }
    }
}

DABanDan/DABanDan/Controllers/DefaultController.cs
using System.Linq;
using System.Web.Mvc;
using DABanDan.Models;
using DABanDan.InputModels.Product;
using DABanDan.DAO;
using System;

namespace DABanDan.Controllers
{
    public class DefaultController : Controller
    {
        Database db = new Database();
        // GET: Index
        public ActionResult Index(string tk)
        {
            var kq = new ProductDao().DanhSachSP(tk).Select(p => new ProductViewModel
            {
                Id = p.MaSP,
                Title = p.TenSP,
                ImageUrl = p.IMG,
                Point = p.DonGia.ToString(),
                Description = p.MoTa,
                Color = p.MauSac,
            });
            var ds = db.SanPhams.OrderByDescending(s => s.MaSP).Select(p => new ProductViewModel
            {
                Id = p.MaSP,
                Title = p.TenSP,
                ImageUrl = p.IMG,
                Point = p.DonGia.ToString(),
                Description = p.MoTa,
                Color = p.MauSac,
                Level = p.Lv
            });
            var results = new ProductIndexModel()
            {
                TimKiem = kq,
                Products = ds
            };
            return View(results);
        }

        public ActionResult Detail(int id)
        {
            var sp = new ProductDao().ViewDetail(id);
            return View( new ProductViewModel()
            {
                Id = sp.MaSP,
                Title = sp.TenSP,
                Color = sp.MauSac,
                Point = sp.DonGia.ToString(),
                ImageUrl = sp.IMG,
                Description = sp.MoTa
       
            });
        }
    }
}

DABanDan/DABanDan/Controllers/ProductController.cs
using DABanDan.DAO;
using DABanDan.InputModels.Product;
using DABanDan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DABanDan.Controllers
{
    public class ProductController : Controller
    {
        Database db = new Database();
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult LoaiSP()
        {
            var model = new ProductCategoryDao().ListALL();
            return PartialView(model);
        }

        [ChildActionOnly]
        public PartialViewResult HieuSP()
        {
            var model = new ProductCategoryDao().ListALLs();
            return PartialView(model);
        }

        public ActionResult TTLoaiSP(string ml , int page = 1, int pageSize = 4)
        {
            var kq = new CategoryDao().ViewDetail(ml);
            ViewBag.TTLoaiSP = kq;
            int totalRecord = 0;
            var model = new ProductDao().DSLoaiSP(ml,ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return View(model);
        }

        public ActionResult TTHieuSP(string mh, int page = 1, int pageSize = 6)
        {
           
         
            int totalRecord = 0;
            var model = new ProductDao().DSHieuSP(mh, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return View(model);
        }

        //-------------------------Tìm Kiếm------------------------------------------------------------
        //public ActionResult TimKiem(string keyword, int page = 1, int pageSize = 4)
        //{
           
        //    int totalRecord = 0;
        //    var model = new ProductDao().Search(keyword, ref totalRecord, page, pageSize);

        //    ViewBag.Total = totalRecord;
        //    ViewBag.Page = page;
        //    ViewBag.Keyword = keyword;
        //    int maxPage = 5;
        //    int totalPage = 0;

        //    totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
        //    ViewBag.TotalPage = totalPage;
        //    ViewBag.MaxPage = maxPage;
        //    ViewBag.First = 1;
        //    ViewBag.Last = totalPage;
        //    ViewBag.Next = page + 1;
        //    ViewBag.Prev = page - 1;
        //    return View(model);
        //}

        //-------------------------Tìm Kiếm DS Liên Quan------------------------------------------------------------
        public ActionResult ResultSearch(string q)
        {
            if (q == null)
            {
                return ViewBag.Result = "Ko có";
            }
            var result = new ProductDao().DanhSachSP(q);
            return View(result);
        }

    }
}

DABanDan/DABanDan/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DABanDan.Models;
using DABanDan.DAO;
using DABanDan.InputModels.Category;
using DABanDan.InputModels.Product;
using System.Web.UI;
using PagedList;

namespace DABanDan.Controllers
{
    public class ShopController : Controller
    {
        Database db = new Database();
        // GET: Shop
        public ActionResult Index()
        {
            var prDao = new ProductDao();
            ViewBag.lvsp = prDao.ListLVSanPham();
            ViewBag.dongiasp = prDao.ListDonGiaSanPham();    
            return View();
        }
    }
}

DABanDan/DABanDan/Views/Shop/Index.cshtml
@model DABanDan.InputModels.Product.ProductIndexModel
@{
    ViewBag.Title = "Trang chủ bán hàng | Shop";
    var lvsp = (List<DABanDan.Models.SanPham>)ViewBag.lvsp;
    var dongiasp = (List<DABanDan.Models.SanPham>)ViewBag.dongiasp;
}
<div class="shop_sidebar_area">
    <!-- ##### CAGETORY ##### -->
    <div class="widget catagory mb-50">
        @{ Html.RenderAction("LoaiSP", "Product");}
    </div>
    <!-- ##### BRAND ##### -->
    <div class="widget brands mb-50">
        @{ Html.RenderAction("HieuSP", "Product");}
    </div>
    <!-- ##### COLOR ##### -->
    <div class="widget color mb-50">
        <!-- Widget Title -->
        <h6 class="widget-title mb-30">Màu Sắc</h6>
        <div class="widget-desc">
            <ul class="d-flex">
                <li><a href="#" class="color3"></a></li>
                <li><a href="#" class="color1"></a></li>
                <li><a href="#" class="color6"></a></li>
                <li><a href="#" class="color7"></a></li>
            </ul>
        </div>
    </div>
</div>

<div class="amado_product_area section-padding-100">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="product-topbar d-xl-flex align-items-end justify-content-between">
                    <!-- SXSorting -->
                    <div class="product-sorting d-flex">
                            <div class="sort-by-date d-flex align-items-center mr-15">
                                <p>Sắp Xếp theo</p>
                                <form action="Index" method="get">
                                    <select name="select" id="">
                                        <option value="value">Giá Guitar</option>
                                        <option value="value">Sản phẩm mới</option>
                                    </select>
                                </form>
                            </div>
                      </div>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- Single Product Area -->
            @foreach (var item in dongiasp)
            {
                <div class="col-12 col-sm-6 col-md-12 col-xl-6">

                    <div class="single-product-wrapper">
                        <!-- Product Image -->

                        <div class="product-img">
                            <a href="@Url.Action("Detail","Default",new {id = @item.MaSP })">
                                <img src="@item.IMG" alt="" style="width: 50%"></a>
                        </div>

                        <!-- Product Description -->
                        <div class="product-description d-flex align-items-center justify-content-between">
                            <!-- Product Meta Data -->


                            <div class="product-meta-data">
                                <div class="line"></div>
                                <a href="@Url.Action("Detail","Default",new {id = @item.MaSP })">
                                    <p style="font-family:'Times New Roman'" class="product-price">@item.DonGia.ToString("#,##0").Replace(',', '.') VND</p>
                                    <h6>@item.TenSP</h6>
                                </a>
                            </div>

                            <!-- Cart -->
                            <div class="ratings-cart text-right">
                                <div class="cart">
                                    <a href="@Url.Action("Index", "Cart")" data-toggle="tooltip" data-placement="left" title="Add to Cart"><img src="~/Content/Client/img/core-img/cart.png" alt=""></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>